name: Deploy Azure Function - exportfindin

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'exportfindin'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3E85A362775E473C90D248EFEA2FD480 }}
        
